inicio
    real kmpercorridos
    real litrosabastecidos
    
    escrever "informar apenas numeros com ponto no lugar da virgula exemplo: 1.0"
    escrever "\nInformar quilometros percorridos: "
    ler kmpercorridos
    escrever "Informar quantidade abastecida: "
    ler litrosabastecidos
    escrever "\nCONSUMO FEITO............:", kmpercorridos/litrosabastecidos,"\t km por litro";
    escrever "\n";    
fim

