inicio

    escrever "\nAlgoritimo para calculo area retangulo"
    escrever "\n"
    escrever "\n#########################################"
    escrever "\n"
    real base
    real altura
    escrever "\nFavor inserir base do retangulo em cm...: "
    ler base
    escrever "Favor inserir altura do retangulo em cm.: "
    ler altura
    
    escrever "AREA DO RETANGULO.......................: ", base*altura, " CM²"
    escrever "\n"
fim